spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-third-party-service
application:
  config:
    product-url: http://localhost:8222/api/v1/products
