version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paung
      - MONGO_INITDB_ROOT_PASSWORD=paung
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "4081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=paung
      - ME_CONFIG_MONGODB_ADMINPASSWORD=paung
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
#      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=paung
      - ME_CONFIG_BASICAUTH_PASSWORD=paung



networks:
  default:
    name: mongodb_network